### ISSUE TITLE
"edited X days ago" Text Inconsistent

### ISSUE THREAD

**Issue by dhkatz** [Xoin/Awfully-White#15]
The text that lets you know a post has been edited seems to have [inconsistent positioning](https://i.imgur.com/8t2ETXR.png).

[Here](https://forum.facepunch.com/f/gmoddev/bsngf/Lua-Help/1/) is the thread in question.

If it helps, using a 2560x1440 screen.

**Comment by Xoin** [comment]
@DoctorJew sorry I spotted this late. Is it still a thing? And which browser are you using. On Chrome it behaves normal for me.
